INSERT INTO CLIENTES (name,lastname,email,create_at) VALUES ('Dacey','Pastor','dictum.magna@elpoliedu.co','2025-01-06');
INSERT INTO CLIENTES (name,lastname,email,create_at) VALUES ('Mariam','Ortega','blandit.nam@elpoliedu.co','2023-12-28');
INSERT INTO CLIENTES (name,lastname,email,create_at) VALUES ('Remedios','Fernandez','nunc.commodo@elpoliedu.co','2024-03-24');
INSERT INTO CLIENTES (name,lastname,email,create_at) VALUES ('Mari','Cortes','tempus.non.lacinia@elpoliedu.co','2023-07-23');
INSERT INTO CLIENTES (name,lastname,email,create_at) VALUES ('Ava','Pastor','lacus@elpoliedu.co','2024-10-17');
INSERT INTO CLIENTES (name,lastname,email,create_at) VALUES ('Althea','Merino','ante@elpoliedu.co','2023-08-24');
INSERT INTO CLIENTES (name,lastname,email,create_at) VALUES ('Cailin','Delgado','massa.integer@elpoliedu.co','2025-06-16');
INSERT INTO CLIENTES (name,lastname,email,create_at) VALUES ('Nina','Diaz','dictum.augue.malesuada@elpoliedu.co','2025-04-18');
INSERT INTO CLIENTES (name,lastname,email,create_at) VALUES ('Anjolie','Muñoz','varius.et@elpoliedu.co','2023-08-18');
INSERT INTO CLIENTES (name,lastname,email,create_at) VALUES ('Rhonda','Martinez','mauris.sapien.cursus@elpoliedu.co','2024-01-31');
INSERT INTO CLIENTES (name,lastname,email,create_at) VALUES ('Lysandra','Marti','proin.mi@elpoliedu.co','2025-05-21');
INSERT INTO CLIENTES (name,lastname,email,create_at) VALUES ('Kimberley','Nieto','augue.eu@elpoliedu.co','2025-01-22');
INSERT INTO CLIENTES (name,lastname,email,create_at) VALUES ('Patience','Nieto','dolor.quam.elementum@elpoliedu.co','2023-09-14');
INSERT INTO CLIENTES (name,lastname,email,create_at) VALUES ('Sarah','Casado','risus@elpoliedu.co','2024-10-04');
INSERT INTO CLIENTES (name,lastname,email,create_at) VALUES ('Ignacio','Herrero','vulputate@elpoliedu.co','2024-07-10');
INSERT INTO CLIENTES (name,lastname,email,create_at) VALUES ('Tatiana','Esteban','nam.ac@elpoliedu.co','2024-10-17');
INSERT INTO CLIENTES (name,lastname,email,create_at) VALUES ('Silvestre','Nieto','eleifend.egestas.sed@elpoliedu.co','2023-10-19');
INSERT INTO CLIENTES (name,lastname,email,create_at) VALUES ('Emilio','Perez','ornare@elpoliedu.co','2023-12-18');
INSERT INTO CLIENTES (name,lastname,email,create_at) VALUES ('Nahuel','Moya','pellentesque@elpoliedu.co','2024-11-23');
INSERT INTO CLIENTES (name,lastname,email,create_at) VALUES ('Antonin','Rubio','dolor.dapibus@elpoliedu.co','2025-08-10');
INSERT INTO CLIENTES (name,lastname,email,create_at) VALUES ('Álvaro','Iba','suspendisse.sagittis@elpoliedu.co','2025-02-01');
INSERT INTO CLIENTES (name,lastname,email,create_at) VALUES ('Maikel','Calvo','adipiscing@elpoliedu.co','2024-10-14');
INSERT INTO CLIENTES (name,lastname,email,create_at) VALUES ('Felipe','Ortiz','elementum.lorem@elpoliedu.co','2023-10-01');
INSERT INTO CLIENTES (name,lastname,email,create_at) VALUES ('Dámaso','Pardo','ac.mattis@elpoliedu.co','2024-08-07');
INSERT INTO CLIENTES (name,lastname,email,create_at) VALUES ('Abraham','Vidal','montes@elpoliedu.co','2024-01-10');
INSERT INTO CLIENTES (name,lastname,email,create_at) VALUES ('Paco','Hernandez','lacus@elpoliedu.co','2024-01-14');
INSERT INTO CLIENTES (name,lastname,email,create_at) VALUES ('Federico','Castro','vel.faucibus.id@elpoliedu.co','2024-01-13');
INSERT INTO CLIENTES (name,lastname,email,create_at) VALUES ('Álvaro','Castillo','ipsum.ac@elpoliedu.co','2023-09-04');
INSERT INTO CLIENTES (name,lastname,email,create_at) VALUES ('Rafa','Marin','dis@elpoliedu.co','2025-09-14');
INSERT INTO CLIENTES (name,lastname,email,create_at) VALUES ('Maximilian','Alvarez','tempus.mauris.erat@elpoliedu.co','2024-04-13');
INSERT INTO PRODUCTOS(name, description, unit_value, stock) VALUES('Producto 1', 'Descripción del producto 1', 1000, 100);
INSERT INTO PRODUCTOS(name, description, unit_value, stock) VALUES('Producto 2', 'Descripción del producto 2', 2000, 200);
INSERT INTO PRODUCTOS(name, description, unit_value, stock) VALUES('Producto 3', 'Descripción del producto 3', 3000, 300);
INSERT INTO PRODUCTOS(name, description, unit_value, stock) VALUES('Producto 4', 'Descripción del producto 4', 4000, 400);
INSERT INTO PRODUCTOS(name, description, unit_value, stock) VALUES('Producto 5', 'Descripción del producto 5', 5000, 500);
INSERT INTO PRODUCTOS(name, description, unit_value, stock) VALUES('Producto 6', 'Descripción del producto 6', 6000, 600);
INSERT INTO PRODUCTOS(name, description, unit_value, stock) VALUES('Producto 7', 'Descripción del producto 7', 7000, 700);
INSERT INTO PRODUCTOS(name, description, unit_value, stock) VALUES('Producto 8', 'Descripción del producto 8', 8000, 800);
INSERT INTO PRODUCTOS(name, description, unit_value, stock) VALUES('Producto 9', 'Descripción del producto 9', 9000, 900);
INSERT INTO PRODUCTOS(name, description, unit_value, stock) VALUES('Producto 10', 'Descripción del producto 10', 10000, 1000);
INSERT INTO PRODUCTOS(name, description, unit_value, stock) VALUES('Producto 11', 'Descripción del producto 11', 11000, 1100);
INSERT INTO PRODUCTOS(name, description, unit_value, stock) VALUES('Producto 12', 'Descripción del producto 12', 12000, 1200);
INSERT INTO PRODUCTOS(name, description, unit_value, stock) VALUES('Producto 13', 'Descripción del producto 13', 13000, 1300);
INSERT INTO PRODUCTOS(name, description, unit_value, stock) VALUES('Producto 14', 'Descripción del producto 14', 14000, 1400);
INSERT INTO PRODUCTOS(name, description, unit_value, stock) VALUES('Producto 15', 'Descripción del producto 15', 15000, 1500);
INSERT INTO PRODUCTOS(name, description, unit_value, stock) VALUES('Producto 16', 'Descripción del producto 16', 16000, 1600);
INSERT INTO PRODUCTOS(name, description, unit_value, stock) VALUES('Producto 17', 'Descripción del producto 17', 17000, 1700);
INSERT INTO PRODUCTOS(name, description, unit_value, stock) VALUES('Producto 18', 'Descripción del producto 18', 18000, 1800);
INSERT INTO PRODUCTOS(name, description, unit_value, stock) VALUES('Producto 19', 'Descripción del producto 19', 19000, 1900);
INSERT INTO PRODUCTOS(name, description, unit_value, stock) VALUES('Producto 20', 'Descripción del producto 20', 20000, 2000);
INSERT INTO PRODUCTOS(name, description, unit_value, stock) VALUES('Producto 21', 'Descripción del producto 21', 21000, 2100);
INSERT INTO PRODUCTOS(name, description, unit_value, stock) VALUES('Producto 22', 'Descripción del producto 22', 22000, 2200);
INSERT INTO PRODUCTOS(name, description, unit_value, stock) VALUES('Producto 23', 'Descripción del producto 23', 23000, 2300);
INSERT INTO PRODUCTOS(name, description, unit_value, stock) VALUES('Producto 24', 'Descripción del producto 24', 24000, 2400);
INSERT INTO PRODUCTOS(name, description, unit_value, stock) VALUES('Producto 25', 'Descripción del producto 25', 25000, 2500);
INSERT INTO PRODUCTOS(name, description, unit_value, stock) VALUES('Producto 26', 'Descripción del producto 26', 26000, 2600);
INSERT INTO PRODUCTOS(name, description, unit_value, stock) VALUES('Producto 27', 'Descripción del producto 27', 27000, 2700);
INSERT INTO PRODUCTOS(name, description, unit_value, stock) VALUES('Producto 28', 'Descripción del producto 28', 28000, 2800);
INSERT INTO PRODUCTOS(name, description, unit_value, stock) VALUES('Producto 29', 'Descripción del producto 29', 29000, 2900);
INSERT INTO PRODUCTOS(name, description, unit_value, stock) VALUES('Producto 30', 'Descripción del producto 30', 30000, 3000);
INSERT INTO VENTAS(cliente_id, producto_id, amount, create_at) VALUES (1, 1, 5, '2024-09-01');
INSERT INTO VENTAS(cliente_id, producto_id, amount, create_at) VALUES (2, 2, 10, '2024-09-02');
INSERT INTO VENTAS(cliente_id, producto_id, amount, create_at) VALUES (3, 3, 3, '2024-09-03');
INSERT INTO VENTAS(cliente_id, producto_id, amount, create_at) VALUES (4, 4, 1, '2024-09-04');
INSERT INTO VENTAS(cliente_id, producto_id, amount, create_at) VALUES (5, 5, 2, '2024-09-05');
INSERT INTO VENTAS(cliente_id, producto_id, amount, create_at) VALUES (6, 6, 7, '2024-09-06');
INSERT INTO VENTAS(cliente_id, producto_id, amount, create_at) VALUES (7, 7, 4, '2024-09-07');
INSERT INTO VENTAS(cliente_id, producto_id, amount, create_at) VALUES (8, 8, 6, '2024-09-08');
INSERT INTO VENTAS(cliente_id, producto_id, amount, create_at) VALUES (9, 9, 8, '2024-09-09');
INSERT INTO VENTAS(cliente_id, producto_id, amount, create_at) VALUES (10, 10, 9, '2024-09-10');
INSERT INTO ENCABEZADO (client_id, sub_total, date, total, total_discount) VALUES (1, 5000, '2024-09-01', 5000, 0);
INSERT INTO ENCABEZADO (client_id, sub_total, date, total, total_discount) VALUES (2, 10000, '2024-09-02', 10000, 0);
INSERT INTO ENCABEZADO (client_id, sub_total, date, total, total_discount) VALUES (3, 3000, '2024-09-03', 3000, 0);
INSERT INTO ENCABEZADO (client_id, sub_total, date, total, total_discount) VALUES (4, 1000, '2024-09-04', 1000, 0);
INSERT INTO ENCABEZADO (client_id, sub_total, date, total, total_discount) VALUES (5, 2000, '2024-09-05', 2000, 0);
INSERT INTO DETALLE (header_id, product_id, quantity, cost, discount) VALUES (1, 1, 5, 1000,0);
INSERT INTO DETALLE (header_id, product_id, quantity, cost, discount) VALUES (2, 2, 10, 2000,0);
INSERT INTO DETALLE (header_id, product_id, quantity, cost, discount) VALUES (3, 3, 3, 3000,0);
INSERT INTO DETALLE (header_id, product_id, quantity, cost, discount) VALUES (4, 4, 1, 4000,0);
INSERT INTO DETALLE (header_id, product_id, quantity, cost, discount) VALUES (5, 5, 2, 5000,0);
